#!/usr/bin/env python3
"""Stamps the build's identity into src/robo_rec/_build_info.py before Nuitka compiles it.

Run by every build script (compile.ps1 / compile.sh / compile.bat / build.py). The generated
module lives inside the robo_rec package, which all four scripts already pass to Nuitka via
--include-package=robo_rec, so it ships in the compiled app with no extra build flags.

Why: a compiled build has no git checkout next to it, so without this a Diagnostics export can't
say which source produced the exe — support was left assuming a client's build matched current
master. Never fails the build: any value it can't determine is written as "unknown".
"""

from __future__ import annotations

import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "src" / "robo_rec" / "_build_info.py"


def _git(*args: str, cwd: Path = REPO_ROOT) -> str:
    try:
        result = subprocess.run(
            ["git", *args], cwd=cwd, capture_output=True, text=True, timeout=30, check=False
        )
    except (OSError, subprocess.SubprocessError):
        return "unknown"
    return result.stdout.strip() if result.returncode == 0 and result.stdout.strip() else "unknown"


def collect() -> dict[str, str | bool]:
    app_commit = _git("rev-parse", "HEAD")
    # Only tracked-file changes count: untracked scratch files (docs/, issues/) don't alter
    # what gets compiled, and treating them as "dirty" would make every build look modified.
    dirty_output = _git("status", "--porcelain", "--untracked-files=no")
    return {
        "app_commit": app_commit,
        "app_commit_short": app_commit[:10] if app_commit != "unknown" else "unknown",
        "app_branch": _git("rev-parse", "--abbrev-ref", "HEAD"),
        "app_dirty": dirty_output not in ("", "unknown"),
        "btcrecover_commit": _git("rev-parse", "HEAD", cwd=REPO_ROOT / "vendor" / "btcrecover"),
        "built_at_utc": datetime.now(UTC).isoformat(timespec="seconds"),
        "built_with_python": sys.version.split()[0],
    }


def main() -> int:
    info = collect()
    OUTPUT.write_text(
        '"""Generated by scripts/write_build_info.py at build time — do not edit or commit."""\n\n'
        f"BUILD_INFO = {info!r}\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)}: app {info['app_commit_short']}"
          f"{' (modified)' if info['app_dirty'] else ''}, "
          f"btcrecover {str(info['btcrecover_commit'])[:10]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
